# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     Robert-Zacchigna/BlackDoc

# Setup
title:            Nakamoto LOL
tagline:          Bitcoin maximalism intersects with nerdcore rap
description:      "Bitcoin maximalist content and weird sci fi nerd rap to go along with it."
url:              http://nakamoto.lol
baseurl:          "/"
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

timezone: America/Chicago

author:
  name:           Chelsea Palmer
  url:            http://chelseakpalmer.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0

github:
  repo:             https://github.com/Robert-Zacchigna/BlackDoc

